package com.bbw.webshopbackend.controller;

import com.bbw.webshopbackend.model.Product;
import com.bbw.webshopbackend.model.ProductRepository;
import com.bbw.webshopbackend.service.Database;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

@Controller // This means that this class is a Controller
public class ProductController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepository productRepository;

    @GetMapping(path="/products")
    public @ResponseBody
    Iterable<Product> getAllProducts() {
        // Create a variable for the connection string.
        Database database = new Database();
        Statement stmt = database.getSqlConnection();
        List<Product> products = new ArrayList<>();
        try {
            String SQL = "SELECT * FROM products";
            ResultSet productResult = null;
            productResult = stmt.executeQuery(SQL);
            while (productResult.next()) {
                Product product = new Product();
                product.setId(productResult.getInt("id"));
                product.setName(productResult.getString("product_name"));
                product.setPrice(productResult.getDouble("product_price"));
                product.setDescription(productResult.getString("product_description"));
                products.add(product);
            }
        }
        catch (SQLException ex) {
            ex.printStackTrace();
        }
        return products;
    }
}
